### ISSUE TITLE
Error while doing reverseGeocoding without optional parameters

### ISSUE THREAD

**Issue by edufpin** [berkayoruc/mapbox_geocoding#1]
```
    ReverseGeocoding reverse = await geocoding
        .reverseModel(-34, 138 );
```

{
    "message": "limit must be combined with a single type parameter when reverse geocoding"
}

There is a default value of 5 in code for limit if it is not set, when using limit a type must be specified.

**Comment by berkayoruc** [comment]
Error fixed last version. Can you check it?
